[package]
name = "align-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "align_lib"
crate-type = ["lib"]

[dependencies]
fancy-regex = "0.13"
regress = "0.9"
unicode-width = "0.1"
directories = "5"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dependencies.indexmap]
version = "=2.2.6"
